cmake_minimum_required(VERSION 3.31)
project(xLR C)

set(CMAKE_C_STANDARD 23)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/output)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/output)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/output)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE INTERNAL "")

if (${CMAKE_SOURCE_DIR} STREQUAL ${CMAKE_CURRENT_SOURCE_DIR})
    set(TARGET_PREFIX "")
else ()
    set(TARGET_PREFIX "xLR_")
endif ()

#add_compile_options("-O3" "-Os")
add_compile_options("-funsigned-char")
add_compile_options("-Wall" "-Wextra" "-Werror")
if (WIN32)
    add_compile_options("-Wno-format")
endif ()
if (ENABLE_TEST_COV)
    add_compile_options("-fprofile-arcs" "-ftest-coverage")
endif ()
if (ENABLE_GPROF)
    add_compile_options("-pg")
    add_link_options("-pg")
endif ()

set(XLR_GENERATED_DIR "${CMAKE_CURRENT_SOURCE_DIR}/grammar/generated")
set(XLR_GEN_TOKEN_ENUM_HEADER "${CMAKE_CURRENT_SOURCE_DIR}/grammar/generated/tokens.gen.h")
if(NOT EXISTS ${XLR_GENERATED_DIR} OR NOT EXISTS ${XLR_TOKEN_ENUM_HEADER})
    message(STATUS "${XLR_GENERATED_DIR} doesn't exist or not complete, generate grammar action table.")
    execute_process(COMMAND /bin/sh ${CMAKE_CURRENT_SOURCE_DIR}/codegen.sh
            WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
else()
    message(STATUS "${XLR_GENERATED_DIR} exists, skip to generate grammar action table.")
endif()

if (NOT TARGET meman)
    include_directories(meman)
    aux_source_directory(meman MEMAN_SRC)
    add_library(meman STATIC ${MEMAN_SRC})
    link_libraries(meman)
endif ()

include_directories(include)

file(GLOB_RECURSE XLR_GRAMMAR_SRC RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} grammar/*.c grammar/*.h)
add_library(${TARGET_PREFIX}grammar STATIC ${XLR_GRAMMAR_SRC})
target_link_libraries(${TARGET_PREFIX}grammar PRIVATE m)
target_include_directories(${TARGET_PREFIX}grammar PRIVATE grammar)


add_executable(${TARGET_PREFIX}debug test/debug.c)
target_link_libraries(${TARGET_PREFIX}debug PRIVATE ${TARGET_PREFIX}grammar)
target_include_directories(${TARGET_PREFIX}debug PRIVATE grammar)


if (BUILD_XLR_TEST)
    add_compile_definitions("XLR_BUILD_TEST=1")
    aux_source_directory(test/test TEST_UTILS_SRC)
    aux_source_directory(test/tokenize TOKENIZE_TEST_SRC)
    add_executable(${TARGET_PREFIX}test-tokenize ${TEST_UTILS_SRC} ${TOKENIZE_TEST_SRC})
    target_link_libraries(${TARGET_PREFIX}test-tokenize PRIVATE ${TARGET_PREFIX}grammar)
    target_include_directories(${TARGET_PREFIX}test-tokenize PRIVATE grammar test)
endif ()
